### ISSUE TITLE
Hook of Residence make Error

### ISSUE THREAD

**Issue by Jecvay** [Jikoo/Regionerator#1]
Hi, I use the plugins for months and it is very amazing! thanks.

as update to 1.4.0, I receive this error:
```

>plugman load Regionerator
[16:22:15 INFO]: [Regionerator] Enabling Regionerator v1.4.0
[16:22:15 INFO]: [Regionerator] Debug level: LOW
[16:22:15 ERROR]: Error occurred while enabling Regionerator v1.4.0 (Is it up to date?)
java.lang.NoSuchMethodError: com.bekvon.bukkit.residence.Residence.getInstance()Lcom/bekvon/bukkit/residence/Residence;
        at com.github.jikoo.regionerator.hooks.ResidenceHook.isChunkProtected(ResidenceHook.java:27) ~[?:?]
        at com.github.jikoo.regionerator.Hook.isHookUsable(Hook.java:25) ~[?:?]
        at com.github.jikoo.regionerator.PluginHook.isHookUsable(PluginHook.java:31) ~[?:?]
        at com.github.jikoo.regionerator.Regionerator.onEnable(Regionerator.java:154) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1040]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1040]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1040]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363) [PlugMan_v2.1.1.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan_v2.1.1.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan_v2.1.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [patched_1.11.2.jar:git-Paper-1040]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) [patched_1.11.2.jar:git-Paper-1040]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675) [patched_1.11.2.jar:git-Paper-1040]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:638) [patched_1.11.2.jar:git-Paper-1040]
        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:441) [patched_1.11.2.jar:git-Paper-1040]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.11.2.jar:git-Paper-1040]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-1040]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-1040]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[16:22:15 INFO]: [Regionerator] Disabling Regionerator v1.4.0

```

And my Residence's version is 4.5.12.2

I really hope this hook works!
thanks again!

**Comment by Jecvay** [comment]
And I test Residence 4.5.13.7, the error still exist.
http://ltcraft.lt/Residence/
