### ISSUE TITLE
Regionerator not detecting ASkyBlock

### ISSUE THREAD

**Issue by andritolion** [Jikoo/Regionerator#6]
Regionerator is not detecting ASkyBlock, and throws a error when detecting.
`[03:00:23 WARN]: java.lang.NullPointerException
[03:00:23 WARN]:        at com.wasteofplastic.askyblock.ASkyBlockAPI.getIslandAt(ASkyBlockAPI.java:475)
[03:00:23 WARN]:        at com.github.jikoo.regionerator.hooks.ASkyBlockHook.isChunkProtected(ASkyBlockHook.java:26)
[03:00:23 WARN]:        at com.github.jikoo.regionerator.Hook.isHookUsable(Hook.java:25)
[03:00:23 WARN]:        at com.github.jikoo.regionerator.PluginHook.isHookUsable(PluginHook.java:31)
[03:00:23 WARN]:        at com.github.jikoo.regionerator.Regionerator.onEnable(Regionerator.java:157)
[03:00:23 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:00:23 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[03:00:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[03:00:23 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[03:00:23 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[03:00:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[03:00:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[03:00:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[03:00:23 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[03:00:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[03:00:23 WARN]:        at java.lang.Thread.run(Thread.java:745)`

**Comment by Jikoo** [comment]
Could you get me logs of a startup please?

**Comment by andritolion** [comment]
Whoops. Didn't see that until just now. Here.
[latest.log](https://github.com/Jikoo/Regionerator/files/1722499/latest.log)

**Comment by Jikoo** [comment]
Looks like ASkyBlock [doesn't set up its grid until 1 tick after startup](https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/ASkyBlock.java#L421). Gotta figure out how I want to handle this, but it's doable.

**Comment by Jikoo** [comment]
[1.5.0](https://github.com/Jikoo/Regionerator/releases/tag/1.5.0)
