### ISSUE TITLE
Not hooking into Factions UUID on 1.16.5

### ISSUE THREAD

**Issue by adamwbb** [Jikoo/Regionerator#74]
Unable to hook into FactionsUUID.
Loadout

```
Regionerator 2.3.0
Factions v1.6.9.5-U0.5.21-b249
Paper version git-Paper-669 (MC: 1.16.5)
```

Console Output

```
[17:03:11] [Server thread/ERROR]: [Regionerator] Unable to enable hook for Factions! Deletion is paused.
java.lang.reflect.InvocationTargetException: null
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
at com.github.jikoo.regionerator.Regionerator.reloadFeatures(Regionerator.java:169) ~[?:?]
at com.github.jikoo.regionerator.Regionerator.onEnable(Regionerator.java:100) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-669]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-669]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-669]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-669]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-669]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:592) ~[patched_1.16.5.jar:git-Paper-669]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-669]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Paper-669]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-669]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/github/jikoo/regionerator/planarwrappers/function/ThrowingTriFunction
at com.github.jikoo.regionerator.hooks.FactionsHook.<init>(FactionsHook.java:37) ~[?:?]
... 17 more
Caused by: java.lang.ClassNotFoundException: com.github.jikoo.regionerator.planarwrappers.function.ThrowingTriFunction
at java.net.URLClassLoader.findClass(URLClassLoader.java:433) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-669]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-669]
at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
at com.github.jikoo.regionerator.hooks.FactionsHook.<init>(FactionsHook.java:37) ~[?:?]
... 17 more
```

**Comment by Jikoo** [comment]
Was fixed in 699e5e008b155d334ad79c92bf51030be8bcbedc, grab any [dev build](https://ci.appveyor.com/project/Jikoo/regionerator/build/artifacts) after that.
