### ISSUE TITLE
Plugin requires WorldEdit

### ISSUE THREAD

**Issue by LucesEnBabel** [Jikoo/Regionerator#9]
```
[02:58:04 ERROR]: Could not load 'plugins/Regionerator.jar' in folder 'plugins'                                                                       
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/worldedit/IncompleteRegionException
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.14.3.jar:git-Paper-128]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[patched_1.14.3.jar:git-Paper-128]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[patched_1.14.3.jar:git-Paper-128]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.3.jar:git-Paper-128]                          
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:218) ~[patched_1.14.3.jar:git-Paper-128]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859) ~[patched_1.14.3.jar:git-Paper-128]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]       
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/IncompleteRegionException
        at com.github.jikoo.regionerator.Regionerator.<init>(Regionerator.java:37) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]                                                       
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:75) ~[patched_1.14.3.jar:git-Paper-128]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.3.jar:git-Paper-128]
        ... 6 more                                                          
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.IncompleteRegionException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.3.jar:git-Paper-128]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.3.jar:git-Paper-128]                           
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]                                                                       
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]            
        at com.github.jikoo.regionerator.Regionerator.<init>(Regionerator.java:37) ~[?:?]                                                              
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_191]             
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:75) ~[patched_1.14.3.jar:git-Paper-128]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.3.jar:git-Paper-128]                          
        ... 6 more
```

Currently running the latest versions of Regionerator and PaperMC (1.14.3).

**Comment by Jikoo** [comment]
Thought I had fixed the hard WorldEdit dependency, whoops.

**Comment by Jikoo** [comment]
[1.5.6](https://github.com/Jikoo/Regionerator/releases/tag/1.5.6)
